#GUI CONFIGURATIONS
PIANO_RELX = 0.02
PIANO_RELY = 0.275
PIANO_RELWIDTH = 0.96
PIANO_RELHEIGHT = 0.65
TOPMENU_RELHEIGHT = 0.2

#SOUNDS FILE CONFIGURATIONS
SOUNDS_COUNT = 10

#GAME CONFIGURATIONS
SOUNDS_COUNT_MINIMUM = 5
SOUNDS_COUNT_MAXIMUM = 50
PIANO_OCTAVE = 4

#GAMEMODES SETTINGS
PRACTICE_GUESS_TIME = 5000 #MS
TIME_FOR_SHOW_ANSWER = 2500 #MS
TOTAL_TIME = PRACTICE_GUESS_TIME + TIME_FOR_SHOW_ANSWER