PIANO_RELX = 0.02
PIANO_RELY = 0.275
PIANO_RELWIDTH = 0.96
PIANO_RELHEIGHT = 0.65
TOPMENU_RELHEIGHT = 0.2

SOUNDS_COUNT = 10
SOUNDS_COUNT_MINIMUM = 2
SOUNDS_COUNT_MAXIMUM = 50

#PRACTICE SETTINGS
TIME_TO_GUESS = 5000 #MS
TIME_FOR_SHOW_ANSWER = 2500 #MS
TOTAL_TIME = TIME_TO_GUESS + TIME_FOR_SHOW_ANSWER